### ISSUE TITLE
Hello , I'm a new to infosphere. Wanna take a try using your process, but met error

### ISSUE THREAD

**Issue by penolove** [joelanford/docker-infosphere-streams#1]
$rake

docker build -t joelanford/infosphere-streams .
Sending build context to Docker daemon 5.065 GB
Step 1 : FROM joelanford/centos7
Pulling repository docker.io/joelanford/centos7
Error while pulling image: Get https://index.docker.io/v1/repositories/joelanford/centos7/images: dial tcp: lookup index.docker.io: no such host
rake aborted!
Command failed with status (1): [docker build -t joelanford/infosphere-stre...]
/home/hduser/docker-infosphere-streams/Rakefile:37:in `block in <top (required)>'
Tasks: TOP => default => build
(See full trace by running task with --trace)

Is there are ways to solve it ?

**Comment by joelanford** [comment]
Give it another shot.  I hadn't pushed my centos7 image up to the docker hub.
